name: app_developments
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  firebase_crashlytics: ^4.0.3
  image_picker: ^0.8.5+3 
  lottie: ^3.1.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  uuid: ^4.5.0
  fl_chart: ^0.69.0
  badword_guard: ^1.0.0

  # bloc
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_screenutil: 5.9.0

  #route
  auto_route: ^7.8.2
  # database
  hive_flutter: ^1.1.0
  #theme

  flavor: ^2.0.0
  # Localization
  flutter_localizations:
    sdk: flutter

  flutter_gen: ^5.3.1
  firebase_analytics: ^11.2.0
  flutter_launcher_icons: ^0.13.1
  tutorial_coach_mark: ^1.2.11
  internet_connection_checker_plus: ^2.5.2
  google_sign_in: ^6.2.1
  permission_handler: ^11.3.1
  path_provider: ^2.1.4

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/png/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.1

  # firebase
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  fluttertoast: ^8.2.6
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: San Francisco 
      fonts:
        - asset: assets/Fonts/SF-Pro.ttf
    - family: Barlow Semi Condensed semi-bold
      fonts:
        - asset: assets/Fonts/BarlowSemiCondensed-SemiBold.ttf
    - family: Barlow Semi Condensed regular
      fonts:
        - asset: assets/Fonts/BarlowSemiCondensed-Regular.ttf
    - family: Barlow Semi Condensed bold
      fonts:
        - asset: assets/Fonts/BarlowSemiCondensed-Bold.ttf

  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/
