name: app_developments
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7

  # bloc
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_screenutil: 5.9.0

  #route
  auto_route: ^7.8.2
  # database
  hive_flutter: ^1.1.0
  #theme

  flavor: ^2.0.0
  # Localization
  intl: any
  flutter_localizations:
    sdk: flutter

  flutter_gen: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/svg/
    - assets/icons/png/
    - assets/images/png/
    - assets/images/svg/
    - assets/
