// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDkTy52oBrP2Gf7g76jH9kSSNs53_hBI4',
    appId: '1:649997249682:web:cb3749f165d4db30058a4b',
    messagingSenderId: '649997249682',
    projectId: 'owemate-41f03',
    authDomain: 'owemate-41f03.firebaseapp.com',
    storageBucket: 'owemate-41f03.appspot.com',
    measurementId: 'G-BH5G8RHHBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaBO3VqPRUraOIuLieGNAcYMpOQ82uzUw',
    appId: '1:649997249682:android:4d993ed5ef2217b9058a4b',
    messagingSenderId: '649997249682',
    projectId: 'owemate-41f03',
    storageBucket: 'owemate-41f03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzBTbdoJdFFtDRxpeS6dNNrQq9kVCvRWY',
    appId: '1:649997249682:ios:893d698eadee9d2a058a4b',
    messagingSenderId: '649997249682',
    projectId: 'owemate-41f03',
    storageBucket: 'owemate-41f03.appspot.com',
    androidClientId: '649997249682-jt6l3h4kmblrp3qv9muhr9bd2lbu15ok.apps.googleusercontent.com',
    iosClientId: '649997249682-sbuk5f02abss4ds2ved68m806ojhg4d3.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDevelopments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzBTbdoJdFFtDRxpeS6dNNrQq9kVCvRWY',
    appId: '1:649997249682:ios:893d698eadee9d2a058a4b',
    messagingSenderId: '649997249682',
    projectId: 'owemate-41f03',
    storageBucket: 'owemate-41f03.appspot.com',
    androidClientId: '649997249682-jt6l3h4kmblrp3qv9muhr9bd2lbu15ok.apps.googleusercontent.com',
    iosClientId: '649997249682-sbuk5f02abss4ds2ved68m806ojhg4d3.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDevelopments',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDkTy52oBrP2Gf7g76jH9kSSNs53_hBI4',
    appId: '1:649997249682:web:773c3436dfea1b54058a4b',
    messagingSenderId: '649997249682',
    projectId: 'owemate-41f03',
    authDomain: 'owemate-41f03.firebaseapp.com',
    storageBucket: 'owemate-41f03.appspot.com',
    measurementId: 'G-BNR2TDWXL7',
  );

}